### ISSUE TITLE
Logo Design Proposal for CookingBook

### ISSUE THREAD

**Issue by happyksu** [funnybobby2/cookingBook#17]
Hi, my name is Ksenia. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo design for your project. If it's something you're interested in, please, let me know!

Best regards,
Ksenia

**Comment by funnybobby2** [comment]
Hello, 
sorry for the response time, I was on vacation (despite some commit ^^). I'm very interested in your proposal! Not being a designer I tried to do my best with what I found... Your help would be very precious :)

**Comment by happyksu** [comment]
Hello!
Happy to hear that :) I'm a little busy right now but for me it will be a pleasure to make design for you.
Can you show me your current logo? (I didn't found it) It also will be great if you will give me link to your cooking book web site or at least screen shoot so it will be easy to understand how it will be placed and choose color palette for logo.
Do you have any special requirements for the logo? Any symbols or text that should be included? And how do you plan to use the logo? On your web site, mobile app and etc?
If you also have ideas or vision how it should look like share them with me :)
Will try to prepare for you few ideas and show you them next week, ok?

**Comment by funnybobby2** [comment]
Hello, great news !
Here is the current design of the site :

![design](https://user-images.githubusercontent.com/26795751/45251788-7369cc80-b34c-11e8-8c9c-8731c2c4cb69.jpg)

The logo is currently 288*234 px in size (with 30 px at the bottom, totally transparent where the user's login in neon mode is dynamically superimposed)
I don't have any particular requirements for the logo, the site is in flat design. It will be as currently put in the top left on the site. The idea is that each person who connects can have the impression of presenting his own menu (hence when connecting the "by Funnybobby" for the funnybobby user)

Thank you in advance for your ideas

**Comment by funnybobby2** [comment]
All images used in my website are here : https://github.com/funnybobby2/cookingBook/tree/master/src/client/assets/img

**Comment by happyksu** [comment]
Hello!
Sorry for delay. Here is few ideas I have for your logo. Please, let me know what do you think? :)
![1](https://user-images.githubusercontent.com/41577905/45627977-bf7ae680-ba9b-11e8-8435-ca95dab674da.jpg)

**Comment by funnybobby2** [comment]
Hello, I love them!!!!! They're really beautiful! My favourites are 1, 2, 3, 4, 5, 7, 9, 10 and 15 (and the 8 but perhaps with a egg more classical in its form like this one with a egg more classical in its form ( like this one https://www.tabtag.com/products/glowing-macbook-sticker-egg-sunny-side-up) ). 
We could use them all and leave the user the choice to customize his page with the one he prefers :)
Excellent work ;)

**Comment by happyksu** [comment]
Hello! Happy that you liked my ideas!
If you don't mind I will share with you some of my thoughts. First of all logo is you brand identity. And if it will be one and unique users will always assosiate it will your website (and may be mobile app one day 😄)
If users can sign in at website we can think about avatars so they can choose one pic they prefer for their profile. It can be sime kind of frame below the logo with login and other details if they needed.
Here is an example of how we can place it.
![mock up](https://user-images.githubusercontent.com/41577905/45680410-8a29d380-bb43-11e8-86e4-cfc8c95d17fd.jpg)

**Comment by funnybobby2** [comment]
Great idea! I really like the font you use. 
I will try to implement this within the week. I'm currently working on a feature to add videos to recipes.

**Comment by happyksu** [comment]
Great! So let's choose one for your logo 😃  or you like that one in the last example?
And what about avatars? Do you want me to make few for your users?

**Comment by funnybobby2** [comment]
The one in the last example suits me very well, it's a good choice:)
If you want to do more avatars it will be with great pleasure!

**Comment by happyksu** [comment]
Hello!
I made few simple user pics. What do you think about this food theme? If everything is ok, I will prepare for you all files tomorrow.
![avatars](https://user-images.githubusercontent.com/41577905/45831420-fd7c4280-bd07-11e8-98c7-40e2924d995c.jpg)

**Comment by funnybobby2** [comment]
Hello !
Awesome! I like it very much. 
Simple and efficient :)

**Comment by happyksu** [comment]
Hello!
Great! I uploaded all the required files and created a pull-request. Please merge it if everything is Ok :)
If you will need font I used you can download it [here](https://fonts.google.com/specimen/Pacifico) .

**Comment by funnybobby2** [comment]
Merged ! Thank you very much for your great job

**Comment by happyksu** [comment]
Thank you for opportunity to work on interesting project:)
Good luck!
